%% fit_and_plot_all.m
%  Fitting a curve and plot the curve and fitting result.
%  author: hxp<hxp201406@gmail.com>
%  Version: MATLAB R2019b Linux


function fit_and_plot_all(lower_limit_1, upper_limit_1, ...
    lower_limit_2, upper_limit_2, FIT_TYPE, ...
    base_line_x_to_electron_volts_zoomed, ...
    base_line_y_zoomed, ...
    transmittance_10min_zoomed, ...
    transmittance_20min_zoomed, ...
    transmittance_30min_zoomed, ...
    transmittance_40min_zoomed)
    figure;
    hold on;

    % plot all figures at once
    plot_all_fig(base_line_x_to_electron_volts_zoomed, ...
            (log((base_line_y_zoomed ./ base_line_y_zoomed).^(-1))).^2, ...
            (log((transmittance_10min_zoomed ./ base_line_y_zoomed).^(-1))).^2, ...
            (log((transmittance_20min_zoomed ./ base_line_y_zoomed).^(-1))).^2, ...
            (log((transmittance_30min_zoomed ./ base_line_y_zoomed).^(-1))).^2, ...
            (log((transmittance_40min_zoomed ./ base_line_y_zoomed).^(-1))).^2, ...
            {'0min', '10min', '20min', '30min', '40min'},...
            'Energy(eV)', '$(\alpha \hbar \omega)^2$', ...
            'Graph Needed to Solve Band Gap', ...
            'northwest');

    fit_all(lower_limit_1, upper_limit_1, FIT_TYPE, ...
        base_line_x_to_electron_volts_zoomed, ...
        base_line_y_zoomed, ...
        transmittance_10min_zoomed, ...
        transmittance_20min_zoomed, ...
        transmittance_30min_zoomed, ...
        transmittance_40min_zoomed)

    fit_all(lower_limit_2, upper_limit_2, FIT_TYPE, ...
        base_line_x_to_electron_volts_zoomed, ...
        base_line_y_zoomed, ...
        transmittance_10min_zoomed, ...
        transmittance_20min_zoomed, ...
        transmittance_30min_zoomed, ...
        transmittance_40min_zoomed);
    xlabel('Energy(eV)', 'Interpreter', 'latex');
    ylabel('$(\alpha \hbar \omega)^2$', 'Interpreter', 'latex');
    title('Graph Needed to Solve Band Gap', 'Interpreter', 'latex');
    legend({'0min', '10min', '20min', '30min', '40min'});
hold off;